server.port=${SERVER_PORT:8080}
server.address=0.0.0.0
spring.servlet.multipart.max-file-size=${SIGNER_MAX_FILE_SIZE:100MB}
spring.servlet.multipart.max-request-size=${SIGNER_MAX_REQUEST_SIZE:110MB}
signer.token=${SIGNER_TOKEN:}
